<a href="https://colab.research.google.com/github/varunbhukya/TNS/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
array=np.array([65,78,90,55,88])
print(array)
average=np.mean(array)
print(average)
print(np.min(array))
max=np.max(array)



[65 78 90 55 88]
75.2
55


1create a numpy array containing numbers 1 to 20 using inbuilt function
2.Create an array of all zeros with 10 elements and convert it to matrix
3.Create an array containing even numbers from 2 to 20
4.create an array and find number of dimensions, shape, size, data type and multiply every elementby 2.
5.Create 1D array and find sum, mean, max and min values

In [ ]:
#1
import numpy as np
array=np.arange(1,21)
print(array)



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
#2
import numpy as np
array=np.zeros((1,11))
print(array)
matrix=np.matrix(array)
print(matrix)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
import numpy as np
array=np.arange(2,21,2)
print(f"even numbers from 2 to 20:{array}")

even numbers from 2 to 20:[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
#4
import numpy as np

array=np.array([[1,2,3,4,5,6,7],[2,3,4,5,6,7,8]])
print(array)
print(array.ndim)
print(array.shape)
print(array.size)
print(array.dtype)
array_multiplied = array * 2
print(array_multiplied)

[[1 2 3 4 5 6 7]
 [2 3 4 5 6 7 8]]
2
(2, 7)
14
int64
[[ 2  4  6  8 10 12 14]
 [ 4  6  8 10 12 14 16]]


In [ ]:
import numpy as np
array=np.arange(1,6)
print(array)
print(array.ndim)
print(array.sum())
print(array.std())
print(array.mean())
print(array.max())
print(array.min())

[1 2 3 4 5]
1
15
1.4142135623730951
3.0
5
1
